// Generated by scripts/gen-snippets.mjs -- do not edit.
export const snippets = {
  "shortcuts": { key: "shortcuts", label: "shortcuts", code: `<KbdGroup>
  <Kbd>Ctrl</Kbd>
  <Kbd>Alt</Kbd>
  <Kbd>Del</Kbd>
</KbdGroup>
<KbdGroup>
  <Kbd>⌘</Kbd>
  <Kbd>Shift</Kbd>
  <Kbd>P</Kbd>
</KbdGroup>`, html: `<pre class="shiki shiki-themes github-light github-dark" style="--shiki-light:#24292e;--shiki-dark:#e1e4e8;--shiki-light-bg:#fff;--shiki-dark-bg:#24292e" tabindex="0"><code><span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">&#x3C;</span><span style="--shiki-light:#B31D28;--shiki-light-font-style:italic;--shiki-dark:#FDAEB7;--shiki-dark-font-style:italic">KbdGroup</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">  &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#85E89D">Kbd</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">>Ctrl&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#85E89D">Kbd</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">  &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#85E89D">Kbd</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">>Alt&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#85E89D">Kbd</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">  &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#85E89D">Kbd</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">>Del&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#85E89D">Kbd</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">&#x3C;/</span><span style="--shiki-light:#B31D28;--shiki-light-font-style:italic;--shiki-dark:#FDAEB7;--shiki-dark-font-style:italic">KbdGroup</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">&#x3C;</span><span style="--shiki-light:#B31D28;--shiki-light-font-style:italic;--shiki-dark:#FDAEB7;--shiki-dark-font-style:italic">KbdGroup</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">  &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#85E89D">Kbd</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">>⌘&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#85E89D">Kbd</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">  &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#85E89D">Kbd</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">>Shift&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#85E89D">Kbd</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">  &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#85E89D">Kbd</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">>P&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#85E89D">Kbd</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">&#x3C;/</span><span style="--shiki-light:#B31D28;--shiki-light-font-style:italic;--shiki-dark:#FDAEB7;--shiki-dark-font-style:italic">KbdGroup</span><span style="--shiki-light:#24292E;--shiki-dark:#E1E4E8">></span></span></code></pre>` },
};
