// Generated by scripts/gen-snippets.mjs -- do not edit.
export const snippets = {
  "default": { key: "default", label: "default", code: `<script>
  import DatePicker from "./components/ui/DatePicker/DatePicker";
</script>

<DatePicker />`, html: `<pre class="shiki shiki-themes min-light material-theme-palenight" style="--shiki-light:#24292eff;--shiki-dark:#babed8;--shiki-light-bg:#ffffff;--shiki-dark-bg:#292D3E" tabindex="0"><code><span class="line"><span style="--shiki-light:#24292EFF;--shiki-dark:#89DDFF">&#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#F07178">script</span><span style="--shiki-light:#24292EFF;--shiki-dark:#89DDFF">></span></span>
<span class="line"><span style="--shiki-light:#D32F2F;--shiki-light-font-style:inherit;--shiki-dark:#89DDFF;--shiki-dark-font-style:italic">  import</span><span style="--shiki-light:#24292EFF;--shiki-dark:#BABED8"> DatePicker </span><span style="--shiki-light:#D32F2F;--shiki-light-font-style:inherit;--shiki-dark:#89DDFF;--shiki-dark-font-style:italic">from</span><span style="--shiki-light:#22863A;--shiki-dark:#89DDFF"> "</span><span style="--shiki-light:#22863A;--shiki-dark:#C3E88D">./components/ui/DatePicker/DatePicker</span><span style="--shiki-light:#22863A;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#24292EFF;--shiki-dark:#89DDFF">;</span></span>
<span class="line"><span style="--shiki-light:#24292EFF;--shiki-dark:#89DDFF">&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#F07178">script</span><span style="--shiki-light:#24292EFF;--shiki-dark:#89DDFF">></span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#24292EFF;--shiki-dark:#89DDFF">&#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#F07178">DatePicker</span><span style="--shiki-light:#24292EFF;--shiki-dark:#89DDFF"> /></span></span></code></pre>` },
};
